FROM tsl0922/musl-cross
RUN git clone --depth=1 https://github.com/tsl0922/ttyd.git /ttyd \
    && cd /ttyd && env BUILD_TARGET=x86_64 WITH_SSL=true ./scripts/cross-build.sh

FROM ubuntu:18.04
COPY --from=0 /ttyd/build/ttyd /usr/bin/ttyd
RUN apt-get update \
    && apt-get install -y tcpdump net-tools dnsutils curl wget apt-transport-https gnupg2 \
    && curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
    && echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list \
    && apt-get update \
    && apt-get install -y kubectl
ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini /sbin/tini
RUN chmod +x /sbin/tini

EXPOSE 7681
ENTRYPOINT ["/sbin/tini", "--"]

# Uncomment below line if using SSL
# CMD ["ttyd", "--ssl", "--ssl-cert", "/etc/ttyd_certs/tls.crt", "--ssl-key", "/etc/ttyd_certs/tls.key", "bash"]
# Uncomment below line if not using SSL
CMD ["ttyd", "bash"]
